/* tslint:disable */
/* eslint-disable */
/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
import type { AxiosInstance, AxiosRequestConfig } from "axios";

export const BASE_PATH = "http://localhost:3000".replace(/\/$/, "");

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
  url: string;
  options: AxiosRequestConfig;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
  protected configuration: Configuration | undefined;
  protected axios: AxiosInstance;
  protected basePath: string;

  constructor(
    configuration?: Configuration,
    basePath?: string,
    axios?: AxiosInstance,
  ) {
    this.configuration = configuration;
    this.basePath = basePath ?? BASE_PATH;
    this.axios = axios as AxiosInstance;
    if (configuration && configuration.basePath) {
      this.basePath = configuration.basePath;
    }
  }
}

export const COLLECTION_FORMATS: { [key: string]: string } = {
  csv: ",",
  ssv: " ",
  tsv: "   ",
  pipes: "|",
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
  override name: "RequiredError" = "RequiredError";
  field: string;

  constructor(field: string, _msg?: string) {
    super(_msg);
    this.field = field;
  }
}
