/* tslint:disable */
/* eslint-disable */
/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AxiosRequestConfig, AxiosInstance } from "axios";
import type { RequestArgs } from "./base";

/**
 * Dummy base URL
 */
export const DUMMY_BASE_URL = "https://example.com";

/**
 * Assert that a parameter is defined
 */
export function assertParamExists(
  funcName: string,
  paramsObj: any,
  paramName: string,
) {
  if (paramsObj && paramsObj[paramName] === undefined) {
    throw new Error(
      `Missing required parameter ${paramName} when calling ${funcName}`,
    );
  }
}

/**
 * Set search params
 */
export function setSearchParams(url: URL, ...objects: any[]) {
  const searchParams = new URLSearchParams();
  for (const obj of objects) {
    for (const key in obj) {
      if (obj[key] !== undefined) {
        searchParams.set(key, String(obj[key]));
      }
    }
  }
  url.search = searchParams.toString();
}

/**
 * Serialize data
 */
export function serializeDataIfNeeded(
  value: any,
  _requestOptions: AxiosRequestConfig,
) {
  if (value && typeof value === "object") {
    if (typeof FormData !== "undefined" && value instanceof FormData) {
      return value;
    }
    if (typeof Blob !== "undefined" && value instanceof Blob) {
      return value;
    }
    if (typeof File !== "undefined" && value instanceof File) {
      return value;
    }
  }
  return value;
}

/**
 * Convert path to string
 */
export function toPathString(url: URL): string {
  return url.pathname + url.search + url.hash;
}

/**
 * Create request function
 */
export function createRequestFunction(
  axiosArgs: RequestArgs,
  globalAxios: AxiosInstance,
  BASE_PATH: string,
  _configuration?: any,
): (...args: any[]) => Promise<any> {
  return async (
    axios: AxiosInstance = globalAxios,
    basePath: string = BASE_PATH,
  ) => {
    const axiosRequestArgs = {
      ...axiosArgs.options,
      url: basePath + axiosArgs.url,
    };
    return axios.request(axiosRequestArgs);
  };
}

/**
 * Set API key to object
 */
export function setApiKeyToObject(obj: any, keyParamName: string, value: any) {
  obj[keyParamName] = value;
}

/**
 * Set basic auth to object
 */
export function setBasicAuthToObject(
  obj: any,
  username: string,
  password: string,
) {
  obj["auth"] = { username, password };
}

/**
 * Set bearer auth to object
 */
export function setBearerAuthToObject(obj: any, token: string) {
  obj["headers"] = obj["headers"] || {};
  obj["headers"]["Authorization"] = `Bearer ${token}`;
}

/**
 * Set OAuth to object
 */
export function setOAuthToObject(
  obj: any,
  _name: string,
  _scopes: string[],
  token: string,
) {
  obj["headers"] = obj["headers"] || {};
  obj["headers"]["Authorization"] = `Bearer ${token}`;
}
