/* tslint:disable */
/* eslint-disable */
/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ApiUsersGet200ResponsePagination } from "./api-users-get200-response-pagination";
// May contain unused imports in some cases
// @ts-ignore
import { User } from "./user";

/**
 *
 * @export
 * @interface ApiUsersGet200Response
 */
export interface ApiUsersGet200Response {
  /**
   *
   * @type {Array<User>}
   * @memberof ApiUsersGet200Response
   */
  users?: Array<User>;
  /**
   *
   * @type {ApiUsersGet200ResponsePagination}
   * @memberof ApiUsersGet200Response
   */
  pagination?: ApiUsersGet200ResponsePagination;
}
