/* tslint:disable */

/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiTestAuthorizedGet200Response
 */
export interface ApiTestAuthorizedGet200Response {
  /**
   *
   * @type {string}
   * @memberof ApiTestAuthorizedGet200Response
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof ApiTestAuthorizedGet200Response
   */
  scope?: string;
  /**
   *
   * @type {string}
   * @memberof ApiTestAuthorizedGet200Response
   */
  userId?: string;
}
