/* tslint:disable */
/* eslint-disable */
/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiUsersGet200ResponsePagination
 */
export interface ApiUsersGet200ResponsePagination {
  /**
   *
   * @type {number}
   * @memberof ApiUsersGet200ResponsePagination
   */
  page?: number;
  /**
   *
   * @type {number}
   * @memberof ApiUsersGet200ResponsePagination
   */
  limit?: number;
  /**
   *
   * @type {number}
   * @memberof ApiUsersGet200ResponsePagination
   */
  total?: number;
  /**
   *
   * @type {number}
   * @memberof ApiUsersGet200ResponsePagination
   */
  pages?: number;
}
