/* tslint:disable */
/* eslint-disable */
/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuthMockLoginPostRequest
 */
export interface AuthMockLoginPostRequest {
  /**
   *
   * @type {string}
   * @memberof AuthMockLoginPostRequest
   */
  userType?: AuthMockLoginPostRequestUserTypeEnum;
  /**
   *
   * @type {string}
   * @memberof AuthMockLoginPostRequest
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof AuthMockLoginPostRequest
   */
  lastName?: string;
}

export const AuthMockLoginPostRequestUserTypeEnum = {
  Agent: "Agent",
  UniversityAdmission: "University_Admission",
  Student: "Student",
  CleverapplyAdmin: "Cleverapply_Admin",
  SubAgent: "Sub_Agent",
  HighSchoolCounselor: "HighSchool_Counselor",
  ServiceProvider: "Service_Provider",
} as const;

export type AuthMockLoginPostRequestUserTypeEnum =
  (typeof AuthMockLoginPostRequestUserTypeEnum)[keyof typeof AuthMockLoginPostRequestUserTypeEnum];
