/* tslint:disable */

/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuthMeGet200ResponseUser
 */
export interface AuthMeGet200ResponseUser {
  /**
   *
   * @type {string}
   * @memberof AuthMeGet200ResponseUser
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof AuthMeGet200ResponseUser
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof AuthMeGet200ResponseUser
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof AuthMeGet200ResponseUser
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof AuthMeGet200ResponseUser
   */
  organizationId?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof AuthMeGet200ResponseUser
   */
  roles?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof AuthMeGet200ResponseUser
   */
  scopes?: Array<string>;
}
