/* tslint:disable */

/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuthLoginPostRequest
 */
export interface AuthLoginPostRequest {
  /**
   *
   * @type {string}
   * @memberof AuthLoginPostRequest
   */
  userId?: string;
  /**
   *
   * @type {string}
   * @memberof AuthLoginPostRequest
   */
  userType?: string;
  /**
   *
   * @type {string}
   * @memberof AuthLoginPostRequest
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof AuthLoginPostRequest
   */
  lastName?: string;
}
