/* tslint:disable */

/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuthStatusGet200Response
 */
export interface AuthStatusGet200Response {
  /**
   *
   * @type {boolean}
   * @memberof AuthStatusGet200Response
   */
  authenticated?: boolean;
  /**
   *
   * @type {object}
   * @memberof AuthStatusGet200Response
   */
  user?: object | null;
  /**
   *
   * @type {string}
   * @memberof AuthStatusGet200Response
   */
  provider?: string;
}
