/* tslint:disable */
/* eslint-disable */
/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AuthMeGet200ResponseOneOf } from "./auth-me-get200-response-one-of";
// May contain unused imports in some cases
// @ts-ignore
import { AuthMeGet200ResponseOneOf1 } from "./auth-me-get200-response-one-of1";
// May contain unused imports in some cases
// @ts-ignore
import { AuthMeGet200ResponseUser } from "./auth-me-get200-response-user";

/**
 * @type AuthMeGet200Response
 * @export
 */
export type AuthMeGet200Response =
  | AuthMeGet200ResponseOneOf
  | AuthMeGet200ResponseOneOf1;
