/* tslint:disable */
/* eslint-disable */
/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuthLoginGet200ResponseOneOf1
 */
export interface AuthLoginGet200ResponseOneOf1 {
  /**
   *
   * @type {string}
   * @memberof AuthLoginGet200ResponseOneOf1
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof AuthLoginGet200ResponseOneOf1
   */
  provider?: string;
}
