/* tslint:disable */

/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuthMockLoginUserIdPost200Response
 */
export interface AuthMockLoginUserIdPost200Response {
  /**
   *
   * @type {boolean}
   * @memberof AuthMockLoginUserIdPost200Response
   */
  success?: boolean;
  /**
   *
   * @type {object}
   * @memberof AuthMockLoginUserIdPost200Response
   */
  user?: object;
}
