/* tslint:disable */

/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ModelError
 */
export interface ModelError {
  /**
   * Error type
   * @type {string}
   * @memberof ModelError
   */
  error: string;
  /**
   * Error description
   * @type {string}
   * @memberof ModelError
   */
  message: string;
  /**
   * Additional error details
   * @type {object}
   * @memberof ModelError
   */
  details?: object;
}
