/* tslint:disable */

/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RateLimitResponse
 */
export interface RateLimitResponse {
  /**
   *
   * @type {string}
   * @memberof RateLimitResponse
   */
  error?: string;
  /**
   *
   * @type {string}
   * @memberof RateLimitResponse
   */
  message?: string;
  /**
   * Seconds to wait before retrying
   * @type {number}
   * @memberof RateLimitResponse
   */
  retryAfter?: number;
}
