/* tslint:disable */
/* eslint-disable */
/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   * Unique user identifier
   * @type {string}
   * @memberof User
   */
  id: string;
  /**
   * User email address
   * @type {string}
   * @memberof User
   */
  email: string;
  /**
   * User full name
   * @type {string}
   * @memberof User
   */
  name: string;
  /**
   * User organization identifier
   * @type {string}
   * @memberof User
   */
  organizationId?: string;
  /**
   * User roles
   * @type {Array<string>}
   * @memberof User
   */
  roles?: Array<string>;
}
