/* tslint:disable */
/* eslint-disable */
/**
 * University Portal API
 * API documentation for the University Portal backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@university-portal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from "axios";
import globalAxios from "axios";
import {
  DUMMY_BASE_URL,
  setSearchParams,
  toPathString,
  createRequestFunction,
} from "../common.ts";
import { BASE_PATH, BaseAPI } from "../base.ts";
import type { RequestArgs } from "../base";
import type {
  ApiTestAnonymousGet200Response,
  ApiTestAuthenticatedGet200Response,
  ApiTestAuthorizedGet200Response,
} from "../models";
/**
 * TestApi - axios parameter creator
 * @export
 */
export const TestApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Test endpoint accessible to everyone without authentication
     * @summary Anonymous API endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiTestAnonymousGet: async (
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/test/anonymous`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Test endpoint that requires authentication
     * @summary Authenticated API endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiTestAuthenticatedGet: async (
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/test/authenticated`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication sessionAuth required

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Test endpoint that requires specific OAuth scope permission
     * @summary Authorized API endpoint (requires specific scope)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiTestAuthorizedGet: async (
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/test/authorized`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication sessionAuth required

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * TestApi - functional programming interface
 * @export
 */
export const TestApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = TestApiAxiosParamCreator(configuration);
  return {
    /**
     * Test endpoint accessible to everyone without authentication
     * @summary Anonymous API endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiTestAnonymousGet(
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiTestAnonymousGet200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiTestAnonymousGet(options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     * Test endpoint that requires authentication
     * @summary Authenticated API endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiTestAuthenticatedGet(
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiTestAuthenticatedGet200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiTestAuthenticatedGet(options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     * Test endpoint that requires specific OAuth scope permission
     * @summary Authorized API endpoint (requires specific scope)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiTestAuthorizedGet(
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiTestAuthorizedGet200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiTestAuthorizedGet(options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * TestApi - factory interface
 * @export
 */
export const TestApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = TestApiFp(configuration);
  return {
    /**
     * Test endpoint accessible to everyone without authentication
     * @summary Anonymous API endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiTestAnonymousGet(
      options?: any,
    ): AxiosPromise<ApiTestAnonymousGet200Response> {
      return localVarFp
        .apiTestAnonymousGet(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Test endpoint that requires authentication
     * @summary Authenticated API endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiTestAuthenticatedGet(
      options?: any,
    ): AxiosPromise<ApiTestAuthenticatedGet200Response> {
      return localVarFp
        .apiTestAuthenticatedGet(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Test endpoint that requires specific OAuth scope permission
     * @summary Authorized API endpoint (requires specific scope)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiTestAuthorizedGet(
      options?: any,
    ): AxiosPromise<ApiTestAuthorizedGet200Response> {
      return localVarFp
        .apiTestAuthorizedGet(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * TestApi - object-oriented interface
 * @export
 * @class TestApi
 * @extends {BaseAPI}
 */
export class TestApi extends BaseAPI {
  /**
   * Test endpoint accessible to everyone without authentication
   * @summary Anonymous API endpoint
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TestApi
   */
  public apiTestAnonymousGet(options?: AxiosRequestConfig) {
    return TestApiFp(this.configuration)
      .apiTestAnonymousGet(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Test endpoint that requires authentication
   * @summary Authenticated API endpoint
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TestApi
   */
  public apiTestAuthenticatedGet(options?: AxiosRequestConfig) {
    return TestApiFp(this.configuration)
      .apiTestAuthenticatedGet(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Test endpoint that requires specific OAuth scope permission
   * @summary Authorized API endpoint (requires specific scope)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TestApi
   */
  public apiTestAuthorizedGet(options?: AxiosRequestConfig) {
    return TestApiFp(this.configuration)
      .apiTestAuthorizedGet(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
